# SPDX-FileCopyrightText: Copyright (c) <2026> NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

# This file is autogenerated, please do not edit.

from __future__ import annotations

from typing import get_args

from cuda.lang._stub._nvvm_mlir_support import ArgSpec, ResultSpec, nvvm_mlir_interface_stub
from cuda.lang._stub.nvvm import (
    B,
    BF16,
    F16,
    F32,
    F64,
    I8,
    I16,
    I32,
    I64,
    IX,
    P0,
    P1,
    P3,
    P4,
    P5,
    P6,
    P7,
    PX,
    U32,
    U64,
    VX,
    X,
)
from cuda.lang._mlir.nvvm import (
    CTAGroupKind,
    CacheEvictionPriority,
    FPRoundingMode,
    GridDepActionKind,
    LoadCacheModifierKind,
    MemOrderKind,
    MemScopeKind,
    PermuteMode,
    PrefetchCacheLevel,
    ProxyKind,
    SaturationMode,
    SetMaxRegisterAction,
    SharedSpace,
    TMALoadMode,
    TMAReduxKind,
    TMAStoreMode,
    Tcgen05CpMulticast,
    Tcgen05CpShape,
    Tcgen05CpSrcFormat,
    Tcgen05FenceKind,
    Tcgen05MMABlockScale,
    Tcgen05MMACollectorBBuffer,
    Tcgen05MMACollectorOp,
    Tcgen05MMAKind,
    Tcgen05WaitKind,
)


def strip(type_hint):
    args = get_args(type_hint)
    return args[1] if len(args) == 2 else type_hint

@nvvm_mlir_interface_stub(
    op_name='nvvm.bar.warp.sync',
    args=(ArgSpec(type=strip(I32), name='mask'),),
)
def bar_warp_sync(*, mask: I32) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.barrier.arrive',
    args=(ArgSpec(type=strip(I32), name='barrierId', optional=True), ArgSpec(type=strip(I32), name='numberOfThreads'),),
)
def barrier_arrive(*, barrier_id: I32 | None = None, number_of_threads: I32) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.breakpoint',
)
def breakpoint() -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.cluster.arrive',
    args=(ArgSpec(type=strip(B), name='aligned', kind='attribute', optional=True, unit=True),),
)
def cluster_arrive(*, aligned: B | None = None) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.cluster.arrive.relaxed',
    args=(ArgSpec(type=strip(B), name='aligned', kind='attribute', optional=True, unit=True),),
)
def cluster_arrive_relaxed(*, aligned: B | None = None) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.cluster.wait',
    args=(ArgSpec(type=strip(B), name='aligned', kind='attribute', optional=True, unit=True),),
)
def cluster_wait(*, aligned: B | None = None) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.clusterlaunchcontrol.try.cancel',
    args=(ArgSpec(type=strip(B), name='multicast', kind='attribute', optional=True, unit=True), ArgSpec(type=strip(P3), name='smemAddress'), ArgSpec(type=strip(P3), name='mbarrier'),),
)
def clusterlaunchcontrol_try_cancel(*, multicast: B | None = None, smem_address: P3, mbarrier: P3) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.convert.float.to.tf32',
    results=(ResultSpec(name='res', type=strip(I32)),),
    args=(ArgSpec(type=strip(F32), name='src'), ArgSpec(type=strip(FPRoundingMode), name='rnd', kind='attribute'), ArgSpec(type=strip(SaturationMode), name='sat', kind='attribute'), ArgSpec(type=strip(B), name='relu', kind='attribute'),),
)
def convert_float_to_tf32(*, src: F32, rnd: FPRoundingMode = FPRoundingMode.NONE, sat: SaturationMode = SaturationMode.NONE, relu: B = False) -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.cos',
    results=(ResultSpec(name='res', type=strip(F32)),),
    args=(ArgSpec(type=strip(F32), name='src'), ArgSpec(type=strip(B), name='ftz', kind='attribute'),),
)
def cos(*, src: F32, ftz: B = False) -> F32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.cp.async.bulk.commit.group',
)
def cp_async_bulk_commit_group() -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.cp.async.bulk.global.shared.cta',
    attr_sized_operand_segments=True,
    args=(ArgSpec(type=strip(P1), name='dstMem'), ArgSpec(type=strip(P3), name='srcMem'), ArgSpec(type=strip(I32), name='size'), ArgSpec(type=strip(I64), name='l2CacheHint', optional=True), ArgSpec(type=strip(I16), name='byteMask', optional=True),),
)
def cp_async_bulk_global_shared_cta(*, dst_mem: P1, src_mem: P3, size: I32, l2_cache_hint: I64 | None = None, byte_mask: I16 | None = None) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.cp.async.bulk.prefetch',
    args=(ArgSpec(type=strip(P1), name='srcMem'), ArgSpec(type=strip(I32), name='size'), ArgSpec(type=strip(I64), name='l2CacheHint', optional=True),),
)
def cp_async_bulk_prefetch(*, src_mem: P1, size: I32, l2_cache_hint: I64 | None = None) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.cp.async.bulk.shared.cluster.global',
    attr_sized_operand_segments=True,
    args=(ArgSpec(type=(strip(P3), strip(P7),), name='dstMem'), ArgSpec(type=strip(P1), name='srcMem'), ArgSpec(type=strip(P3), name='mbar'), ArgSpec(type=strip(I32), name='size'), ArgSpec(type=strip(I16), name='multicastMask', optional=True), ArgSpec(type=strip(I64), name='l2CacheHint', optional=True),),
)
def cp_async_bulk_shared_cluster_global(*, dst_mem: P3 | P7, src_mem: P1, mbar: P3, size: I32, multicast_mask: I16 | None = None, l2_cache_hint: I64 | None = None) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.cp.async.bulk.shared.cluster.shared.cta',
    args=(ArgSpec(type=strip(P7), name='dstMem'), ArgSpec(type=strip(P3), name='srcMem'), ArgSpec(type=strip(P3), name='mbar'), ArgSpec(type=strip(I32), name='size'),),
)
def cp_async_bulk_shared_cluster_shared_cta(*, dst_mem: P7, src_mem: P3, mbar: P3, size: I32) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.cp.async.bulk.tensor.global.shared.cta',
    attr_sized_operand_segments=True,
    args=(ArgSpec(type=strip(P0), name='tmaDescriptor'), ArgSpec(type=strip(P3), name='srcMem'), ArgSpec(type=strip(I32), name='coordinates', variadic=True), ArgSpec(type=strip(I64), name='l2CacheHint', optional=True), ArgSpec(type=strip(TMAStoreMode), name='mode', kind='attribute'), ArgSpec(type=strip(B), name='predicate', optional=True),),
)
def cp_async_bulk_tensor_global_shared_cta(*, tma_descriptor: P0, src_mem: P3, coordinates: tuple[I32, ...], l2_cache_hint: I64 | None = None, mode: TMAStoreMode = TMAStoreMode.TILE, predicate: B | None = None) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.cp.async.bulk.tensor.prefetch',
    attr_sized_operand_segments=True,
    args=(ArgSpec(type=strip(P0), name='tmaDescriptor'), ArgSpec(type=strip(I32), name='coordinates', variadic=True), ArgSpec(type=strip(I16), name='im2colOffsets', variadic=True), ArgSpec(type=strip(TMALoadMode), name='mode', kind='attribute'), ArgSpec(type=strip(I64), name='l2CacheHint', optional=True),),
)
def cp_async_bulk_tensor_prefetch(*, tma_descriptor: P0, coordinates: tuple[I32, ...], im2col_offsets: tuple[I16, ...], mode: TMALoadMode = TMALoadMode.TILE, l2_cache_hint: I64 | None = None) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.cp.async.bulk.tensor.reduce',
    attr_sized_operand_segments=True,
    args=(ArgSpec(type=strip(PX), name='tmaDescriptor'), ArgSpec(type=strip(P3), name='srcMem'), ArgSpec(type=strip(TMAReduxKind), name='redKind', kind='attribute'), ArgSpec(type=strip(TMAStoreMode), name='mode', kind='attribute'), ArgSpec(type=strip(I32), name='coordinates', variadic=True), ArgSpec(type=strip(I64), name='l2CacheHint', optional=True),),
)
def cp_async_bulk_tensor_reduce(*, tma_descriptor: PX, src_mem: P3, red_kind: TMAReduxKind, mode: TMAStoreMode = TMAStoreMode.TILE, coordinates: tuple[I32, ...], l2_cache_hint: I64 | None = None) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.cp.async.bulk.tensor.shared.cluster.global',
    attr_sized_operand_segments=True,
    args=(ArgSpec(type=(strip(P3), strip(P7),), name='dstMem'), ArgSpec(type=strip(P0), name='tmaDescriptor'), ArgSpec(type=strip(I32), name='coordinates', variadic=True), ArgSpec(type=strip(P3), name='mbar'), ArgSpec(type=strip(I16), name='im2colOffsets', variadic=True), ArgSpec(type=strip(I16), name='multicastMask', optional=True), ArgSpec(type=strip(I64), name='l2CacheHint', optional=True), ArgSpec(type=strip(TMALoadMode), name='mode', kind='attribute'), ArgSpec(type=strip(B), name='isCTAOnly', kind='attribute'), ArgSpec(type=strip(CTAGroupKind), name='group', kind='attribute', optional=True), ArgSpec(type=strip(B), name='predicate', optional=True),),
)
def cp_async_bulk_tensor_shared_cluster_global(*, dst_mem: P3 | P7, tma_descriptor: P0, coordinates: tuple[I32, ...], mbar: P3, im2col_offsets: tuple[I16, ...], multicast_mask: I16 | None = None, l2_cache_hint: I64 | None = None, mode: TMALoadMode = TMALoadMode.TILE, is_c_t_a_only: B = False, group: CTAGroupKind | None = None, predicate: B | None = None) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.cp.async.bulk.wait_group',
    args=(ArgSpec(type=strip(U32), name='group', kind='attribute'), ArgSpec(type=strip(B), name='read', kind='attribute', optional=True, unit=True),),
)
def cp_async_bulk_wait_group(*, group: U32, read: B | None = None) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.cp.async.commit.group',
)
def cp_async_commit_group() -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.cp.async.mbarrier.arrive',
    args=(ArgSpec(type=(strip(P0), strip(P3),), name='addr'), ArgSpec(type=strip(B), name='noinc', kind='attribute'),),
)
def cp_async_mbarrier_arrive(*, addr: P0 | P3, noinc: B = 0) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.cp.async.shared.global',
    args=(ArgSpec(type=strip(P3), name='dst'), ArgSpec(type=strip(P1), name='src'), ArgSpec(type=strip(U32), name='size', kind='attribute'), ArgSpec(type=strip(LoadCacheModifierKind), name='modifier', kind='attribute'), ArgSpec(type=strip(I32), name='cpSize', optional=True),),
)
def cp_async_shared_global(*, dst: P3, src: P1, size: U32, modifier: LoadCacheModifierKind, cp_size: I32 | None = None) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.cp.async.wait.group',
    args=(ArgSpec(type=strip(U32), name='n', kind='attribute'),),
)
def cp_async_wait_group(*, n: U32) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.elect.sync',
    results=(ResultSpec(name='pred', type=strip(B)),),
    args=(ArgSpec(type=strip(I32), name='membermask', optional=True),),
)
def elect_sync(*, membermask: I32 | None = None) -> B: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.ex2',
    results=(ResultSpec(name='res', type=strip(F32)),),
    args=(ArgSpec(type=strip(F32), name='src'), ArgSpec(type=strip(B), name='ftz', kind='attribute'),),
)
def ex2(*, src: F32, ftz: B = False) -> F32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.exit',
)
def exit() -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.fence.mbarrier.init',
)
def fence_mbarrier_init() -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.fence.proxy',
    args=(ArgSpec(type=strip(ProxyKind), name='kind', kind='attribute'), ArgSpec(type=strip(SharedSpace), name='space', kind='attribute', optional=True),),
)
def fence_proxy(*, kind: ProxyKind, space: SharedSpace | None = None) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.fence.proxy.acquire',
    args=(ArgSpec(type=strip(MemScopeKind), name='scope', kind='attribute'), ArgSpec(type=strip(P0), name='addr'), ArgSpec(type=strip(I32), name='size'), ArgSpec(type=strip(ProxyKind), name='fromProxy', kind='attribute'), ArgSpec(type=strip(ProxyKind), name='toProxy', kind='attribute'),),
)
def fence_proxy_acquire(*, scope: MemScopeKind, addr: P0, size: I32, from_proxy: ProxyKind = ProxyKind.GENERIC, to_proxy: ProxyKind = ProxyKind.TENSORMAP) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.fence.proxy.release',
    args=(ArgSpec(type=strip(MemScopeKind), name='scope', kind='attribute'), ArgSpec(type=strip(ProxyKind), name='fromProxy', kind='attribute'), ArgSpec(type=strip(ProxyKind), name='toProxy', kind='attribute'),),
)
def fence_proxy_release(*, scope: MemScopeKind, from_proxy: ProxyKind = ProxyKind.GENERIC, to_proxy: ProxyKind = ProxyKind.TENSORMAP) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.fence.proxy.sync_restrict',
    args=(ArgSpec(type=strip(MemOrderKind), name='order', kind='attribute'), ArgSpec(type=strip(ProxyKind), name='fromProxy', kind='attribute'), ArgSpec(type=strip(ProxyKind), name='toProxy', kind='attribute'),),
)
def fence_proxy_sync_restrict(*, order: MemOrderKind, from_proxy: ProxyKind = ProxyKind.GENERIC, to_proxy: ProxyKind = ProxyKind.async_) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.fence.sc.cluster',
)
def fence_sc_cluster() -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.fence.sync_restrict',
    args=(ArgSpec(type=strip(MemOrderKind), name='order', kind='attribute'),),
)
def fence_sync_restrict(*, order: MemOrderKind) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.griddepcontrol',
    args=(ArgSpec(type=strip(GridDepActionKind), name='kind', kind='attribute'),),
)
def griddepcontrol(*, kind: GridDepActionKind) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.log2',
    results=(ResultSpec(name='res', type=strip(F32)),),
    args=(ArgSpec(type=strip(F32), name='src'), ArgSpec(type=strip(B), name='ftz', kind='attribute'),),
)
def log2(*, src: F32, ftz: B = False) -> F32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.mbarrier.arrive.nocomplete',
    results=(ResultSpec(name='res', type=strip(I64)),),
    args=(ArgSpec(type=(strip(P0), strip(P3),), name='addr'), ArgSpec(type=strip(I32), name='count'),),
)
def mbarrier_arrive_nocomplete(*, addr: P0 | P3, count: I32) -> I64: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.mbarrier.arrive_drop.nocomplete',
    results=(ResultSpec(name='res', type=strip(I64)),),
    args=(ArgSpec(type=(strip(P0), strip(P3),), name='addr'), ArgSpec(type=strip(I32), name='count'),),
)
def mbarrier_arrive_drop_nocomplete(*, addr: P0 | P3, count: I32) -> I64: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.mbarrier.complete_tx',
    args=(ArgSpec(type=(strip(P3), strip(P7),), name='addr'), ArgSpec(type=strip(I32), name='txcount'), ArgSpec(type=strip(MemScopeKind), name='scope', kind='attribute'),),
)
def mbarrier_complete_tx(*, addr: P3 | P7, txcount: I32, scope: MemScopeKind = MemScopeKind.CTA) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.mbarrier.expect_tx',
    args=(ArgSpec(type=(strip(P3), strip(P7),), name='addr'), ArgSpec(type=strip(I32), name='txcount'), ArgSpec(type=strip(MemScopeKind), name='scope', kind='attribute'),),
)
def mbarrier_expect_tx(*, addr: P3 | P7, txcount: I32, scope: MemScopeKind = MemScopeKind.CTA) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.mbarrier.init',
    args=(ArgSpec(type=(strip(P0), strip(P3),), name='addr'), ArgSpec(type=strip(I32), name='count'), ArgSpec(type=strip(B), name='predicate', optional=True),),
)
def mbarrier_init(*, addr: P0 | P3, count: I32, predicate: B | None = None) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.mbarrier.inval',
    args=(ArgSpec(type=(strip(P0), strip(P3),), name='addr'),),
)
def mbarrier_inval(*, addr: P0 | P3) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.mbarrier.test.wait',
    results=(ResultSpec(name='res', type=strip(B)),),
    args=(ArgSpec(type=(strip(P0), strip(P3),), name='addr'), ArgSpec(type=(strip(I64), strip(I32),), name='stateOrPhase'), ArgSpec(type=strip(MemScopeKind), name='scope', kind='attribute'), ArgSpec(type=strip(B), name='relaxed', kind='attribute'),),
)
def mbarrier_test_wait(*, addr: P0 | P3, state_or_phase: I64 | I32, scope: MemScopeKind = MemScopeKind.CTA, relaxed: B = False) -> B: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.mbarrier.try_wait',
    results=(ResultSpec(name='res', type=strip(B)),),
    args=(ArgSpec(type=(strip(P0), strip(P3),), name='addr'), ArgSpec(type=(strip(I64), strip(I32),), name='stateOrPhase'), ArgSpec(type=strip(I32), name='ticks', optional=True), ArgSpec(type=strip(MemScopeKind), name='scope', kind='attribute'), ArgSpec(type=strip(B), name='relaxed', kind='attribute'),),
)
def mbarrier_try_wait(*, addr: P0 | P3, state_or_phase: I64 | I32, ticks: I32 | None = None, scope: MemScopeKind = MemScopeKind.CTA, relaxed: B = False) -> B: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.mbarrier.try_wait.parity',
    args=(ArgSpec(type=(strip(P0), strip(P3),), name='addr'), ArgSpec(type=strip(I32), name='phase'), ArgSpec(type=strip(I32), name='ticks'),),
)
def mbarrier_try_wait_parity(*, addr: P0 | P3, phase: I32, ticks: I32) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.memory.barrier',
    args=(ArgSpec(type=strip(MemScopeKind), name='scope', kind='attribute'),),
)
def memory_barrier(*, scope: MemScopeKind) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.nanosleep',
    args=(ArgSpec(type=strip(I32), name='duration'),),
)
def nanosleep(*, duration: I32) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.prefetch',
    args=(ArgSpec(type=strip(PrefetchCacheLevel), name='cacheLevel', kind='attribute', optional=True), ArgSpec(type=strip(CacheEvictionPriority), name='evictPriority', kind='attribute', optional=True), ArgSpec(type=(strip(P1), strip(P5), strip(P0), strip(P4),), name='addr'), ArgSpec(type=strip(B), name='predicate', optional=True), ArgSpec(type=strip(B), name='tensormap', kind='attribute', optional=True, unit=True), ArgSpec(type=strip(B), name='uniform', kind='attribute', optional=True, unit=True), ArgSpec(type=strip(B), name='in_param_space', kind='attribute', optional=True, unit=True),),
)
def prefetch(*, cache_level: PrefetchCacheLevel | None = None, evict_priority: CacheEvictionPriority | None = None, addr: P1 | P5 | P0 | P4, predicate: B | None = None, tensormap: B | None = None, uniform: B | None = None, in_param_space: B | None = None) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.prmt',
    results=(ResultSpec(name='res', type=strip(I32)),),
    args=(ArgSpec(type=strip(I32), name='lo'), ArgSpec(type=strip(I32), name='hi', optional=True), ArgSpec(type=strip(I32), name='selector'), ArgSpec(type=strip(PermuteMode), name='mode', kind='attribute'),),
)
def prmt(*, lo: I32, hi: I32 | None = None, selector: I32, mode: PermuteMode) -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.rcp.approx.ftz.f',
    results=(ResultSpec(name='res', type=strip(F32)),),
    args=(ArgSpec(type=strip(F32), name='arg'),),
)
def rcp_approx_ftz_f(*, arg: F32) -> F32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.aggr.smem.size',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_aggr_smem_size() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.clock',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_clock() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.clock64',
    results=(ResultSpec(name='res', type=strip(I64)),),
)
def read_ptx_sreg_clock64() -> I64: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.dynamic.smem.size',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_dynamic_smem_size() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg0',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg0() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg1',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg1() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg10',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg10() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg11',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg11() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg12',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg12() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg13',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg13() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg14',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg14() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg15',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg15() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg16',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg16() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg17',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg17() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg18',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg18() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg19',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg19() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg2',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg2() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg20',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg20() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg21',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg21() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg22',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg22() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg23',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg23() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg24',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg24() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg25',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg25() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg26',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg26() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg27',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg27() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg28',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg28() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg29',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg29() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg3',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg3() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg30',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg30() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg31',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg31() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg4',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg4() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg5',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg5() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg6',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg6() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg7',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg7() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg8',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg8() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.envreg9',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_envreg9() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.globaltimer',
    results=(ResultSpec(name='res', type=strip(I64)),),
)
def read_ptx_sreg_globaltimer() -> I64: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.globaltimer.lo',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_globaltimer_lo() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.lanemask.eq',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_lanemask_eq() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.lanemask.ge',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_lanemask_ge() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.lanemask.gt',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_lanemask_gt() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.lanemask.le',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_lanemask_le() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.lanemask.lt',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_lanemask_lt() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.read.ptx.sreg.total.smem.size',
    results=(ResultSpec(name='res', type=strip(I32)),),
)
def read_ptx_sreg_total_smem_size() -> I32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.setmaxregister',
    args=(ArgSpec(type=strip(U32), name='regCount', kind='attribute'), ArgSpec(type=strip(SetMaxRegisterAction), name='action', kind='attribute'),),
)
def setmaxregister(*, reg_count: U32, action: SetMaxRegisterAction) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.sin',
    results=(ResultSpec(name='res', type=strip(F32)),),
    args=(ArgSpec(type=strip(F32), name='src'), ArgSpec(type=strip(B), name='ftz', kind='attribute'),),
)
def sin(*, src: F32, ftz: B = False) -> F32: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.st.bulk',
    args=(ArgSpec(type=(strip(P0), strip(P3),), name='addr'), ArgSpec(type=strip(I64), name='size'), ArgSpec(type=strip(U64), name='initVal', kind='attribute'),),
)
def st_bulk(*, addr: P0 | P3, size: I64, init_val: U64 = 0) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.tcgen05.alloc',
    args=(ArgSpec(type=(strip(PX), strip(P3),), name='addr'), ArgSpec(type=strip(I32), name='nCols'), ArgSpec(type=strip(CTAGroupKind), name='group', kind='attribute'),),
)
def tcgen05_alloc(*, addr: PX | P3, n_cols: I32, group: CTAGroupKind = CTAGroupKind.CTA_1) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.tcgen05.commit',
    args=(ArgSpec(type=(strip(PX), strip(P3),), name='addr'), ArgSpec(type=strip(I16), name='multicastMask', optional=True), ArgSpec(type=strip(CTAGroupKind), name='group', kind='attribute'),),
)
def tcgen05_commit(*, addr: PX | P3, multicast_mask: I16 | None = None, group: CTAGroupKind = CTAGroupKind.CTA_1) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.tcgen05.cp',
    args=(ArgSpec(type=strip(Tcgen05CpShape), name='shape', kind='attribute'), ArgSpec(type=strip(CTAGroupKind), name='group', kind='attribute'), ArgSpec(type=strip(Tcgen05CpMulticast), name='multicast', kind='attribute'), ArgSpec(type=strip(Tcgen05CpSrcFormat), name='srcFormat', kind='attribute', optional=True), ArgSpec(type=strip(P6), name='taddr'), ArgSpec(type=strip(I64), name='smem_desc'),),
)
def tcgen05_cp(*, shape: Tcgen05CpShape, group: CTAGroupKind = CTAGroupKind.CTA_1, multicast: Tcgen05CpMulticast = Tcgen05CpMulticast.NONE, src_format: Tcgen05CpSrcFormat | None = None, taddr: P6, smem_desc: I64) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.tcgen05.dealloc',
    args=(ArgSpec(type=strip(P6), name='taddr'), ArgSpec(type=strip(I32), name='nCols'), ArgSpec(type=strip(CTAGroupKind), name='group', kind='attribute'),),
)
def tcgen05_dealloc(*, taddr: P6, n_cols: I32, group: CTAGroupKind = CTAGroupKind.CTA_1) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.tcgen05.fence',
    args=(ArgSpec(type=strip(Tcgen05FenceKind), name='kind', kind='attribute'),),
)
def tcgen05_fence(*, kind: Tcgen05FenceKind) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.tcgen05.mma.block_scale',
    args=(ArgSpec(type=strip(Tcgen05MMAKind), name='kind', kind='attribute'), ArgSpec(type=strip(CTAGroupKind), name='ctaGroup', kind='attribute'), ArgSpec(type=strip(Tcgen05MMABlockScale), name='blockScale', kind='attribute'), ArgSpec(type=strip(Tcgen05MMACollectorOp), name='collectorOp', kind='attribute'), ArgSpec(type=strip(P6), name='matrixD'), ArgSpec(type=(strip(P6), strip(I64),), name='matrixA'), ArgSpec(type=strip(I64), name='matrixB'), ArgSpec(type=strip(I32), name='idesc'), ArgSpec(type=strip(B), name='enableInputD'), ArgSpec(type=strip(P6), name='scaleA'), ArgSpec(type=strip(P6), name='scaleB'),),
)
def tcgen05_mma_block_scale(*, kind: Tcgen05MMAKind, cta_group: CTAGroupKind, block_scale: Tcgen05MMABlockScale = Tcgen05MMABlockScale.DEFAULT, collector_op: Tcgen05MMACollectorOp = Tcgen05MMACollectorOp.DISCARD, matrix_d: P6, matrix_a: P6 | I64, matrix_b: I64, idesc: I32, enable_input_d: B, scale_a: P6, scale_b: P6) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.tcgen05.mma.sp.block_scale',
    args=(ArgSpec(type=strip(Tcgen05MMAKind), name='kind', kind='attribute'), ArgSpec(type=strip(CTAGroupKind), name='ctaGroup', kind='attribute'), ArgSpec(type=strip(Tcgen05MMABlockScale), name='blockScale', kind='attribute'), ArgSpec(type=strip(Tcgen05MMACollectorOp), name='collectorOp', kind='attribute'), ArgSpec(type=strip(P6), name='matrixD'), ArgSpec(type=(strip(P6), strip(I64),), name='matrixA'), ArgSpec(type=strip(I64), name='matrixB'), ArgSpec(type=strip(I32), name='idesc'), ArgSpec(type=strip(B), name='enableInputD'), ArgSpec(type=strip(P6), name='sparseMetadata'), ArgSpec(type=strip(P6), name='scaleA'), ArgSpec(type=strip(P6), name='scaleB'),),
)
def tcgen05_mma_sp_block_scale(*, kind: Tcgen05MMAKind, cta_group: CTAGroupKind, block_scale: Tcgen05MMABlockScale = Tcgen05MMABlockScale.DEFAULT, collector_op: Tcgen05MMACollectorOp = Tcgen05MMACollectorOp.DISCARD, matrix_d: P6, matrix_a: P6 | I64, matrix_b: I64, idesc: I32, enable_input_d: B, sparse_metadata: P6, scale_a: P6, scale_b: P6) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.tcgen05.mma.ws',
    args=(ArgSpec(type=strip(Tcgen05MMAKind), name='kind', kind='attribute'), ArgSpec(type=strip(Tcgen05MMACollectorBBuffer), name='collectorBBuffer', kind='attribute'), ArgSpec(type=strip(Tcgen05MMACollectorOp), name='collectorOp', kind='attribute'), ArgSpec(type=strip(P6), name='matrixD'), ArgSpec(type=(strip(P6), strip(I64),), name='matrixA'), ArgSpec(type=strip(I64), name='matrixB'), ArgSpec(type=strip(I32), name='idesc'), ArgSpec(type=strip(B), name='enableInputD'), ArgSpec(type=strip(I64), name='zeroColMask', optional=True),),
)
def tcgen05_mma_ws(*, kind: Tcgen05MMAKind, collector_b_buffer: Tcgen05MMACollectorBBuffer = Tcgen05MMACollectorBBuffer.B0, collector_op: Tcgen05MMACollectorOp = Tcgen05MMACollectorOp.DISCARD, matrix_d: P6, matrix_a: P6 | I64, matrix_b: I64, idesc: I32, enable_input_d: B, zero_col_mask: I64 | None = None) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.tcgen05.mma.ws.sp',
    args=(ArgSpec(type=strip(Tcgen05MMAKind), name='kind', kind='attribute'), ArgSpec(type=strip(Tcgen05MMACollectorBBuffer), name='collectorBBuffer', kind='attribute'), ArgSpec(type=strip(Tcgen05MMACollectorOp), name='collectorOp', kind='attribute'), ArgSpec(type=strip(P6), name='matrixD'), ArgSpec(type=(strip(P6), strip(I64),), name='matrixA'), ArgSpec(type=strip(I64), name='matrixB'), ArgSpec(type=strip(I32), name='idesc'), ArgSpec(type=strip(B), name='enableInputD'), ArgSpec(type=strip(P6), name='sparseMetadata'), ArgSpec(type=strip(I64), name='zeroColMask', optional=True),),
)
def tcgen05_mma_ws_sp(*, kind: Tcgen05MMAKind, collector_b_buffer: Tcgen05MMACollectorBBuffer = Tcgen05MMACollectorBBuffer.B0, collector_op: Tcgen05MMACollectorOp = Tcgen05MMACollectorOp.DISCARD, matrix_d: P6, matrix_a: P6 | I64, matrix_b: I64, idesc: I32, enable_input_d: B, sparse_metadata: P6, zero_col_mask: I64 | None = None) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.tcgen05.mma_smem_desc',
    results=(ResultSpec(name='res', type=strip(I64)),),
    args=(ArgSpec(type=strip(I32), name='startAddr'), ArgSpec(type=strip(I32), name='leadingDimOffset'), ArgSpec(type=strip(I32), name='strideDimOffset'), ArgSpec(type=strip(I8), name='baseOffset'), ArgSpec(type=strip(B), name='leadingDimMode'), ArgSpec(type=strip(I8), name='swizzleMode'),),
)
def tcgen05_mma_smem_desc(*, start_addr: I32, leading_dim_offset: I32, stride_dim_offset: I32, base_offset: I8, leading_dim_mode: B, swizzle_mode: I8) -> I64: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.tcgen05.relinquish_alloc_permit',
    args=(ArgSpec(type=strip(CTAGroupKind), name='group', kind='attribute'),),
)
def tcgen05_relinquish_alloc_permit(*, group: CTAGroupKind = CTAGroupKind.CTA_1) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.tcgen05.shift',
    args=(ArgSpec(type=strip(P6), name='taddr'), ArgSpec(type=strip(CTAGroupKind), name='group', kind='attribute'),),
)
def tcgen05_shift(*, taddr: P6, group: CTAGroupKind = CTAGroupKind.CTA_1) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.tcgen05.wait',
    args=(ArgSpec(type=strip(Tcgen05WaitKind), name='kind', kind='attribute'),),
)
def tcgen05_wait(*, kind: Tcgen05WaitKind) -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.wgmma.commit.group.sync.aligned',
)
def wgmma_commit_group_sync_aligned() -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.wgmma.fence.aligned',
)
def wgmma_fence_aligned() -> None: ...

@nvvm_mlir_interface_stub(
    op_name='nvvm.wgmma.wait.group.sync.aligned',
    args=(ArgSpec(type=strip(U64), name='group', kind='attribute'),),
)
def wgmma_wait_group_sync_aligned(*, group: U64) -> None: ...

__all__ = (
    'bar_warp_sync',
    'barrier_arrive',
    'breakpoint',
    'cluster_arrive',
    'cluster_arrive_relaxed',
    'cluster_wait',
    'clusterlaunchcontrol_try_cancel',
    'convert_float_to_tf32',
    'cos',
    'cp_async_bulk_commit_group',
    'cp_async_bulk_global_shared_cta',
    'cp_async_bulk_prefetch',
    'cp_async_bulk_shared_cluster_global',
    'cp_async_bulk_shared_cluster_shared_cta',
    'cp_async_bulk_tensor_global_shared_cta',
    'cp_async_bulk_tensor_prefetch',
    'cp_async_bulk_tensor_reduce',
    'cp_async_bulk_tensor_shared_cluster_global',
    'cp_async_bulk_wait_group',
    'cp_async_commit_group',
    'cp_async_mbarrier_arrive',
    'cp_async_shared_global',
    'cp_async_wait_group',
    'elect_sync',
    'ex2',
    'exit',
    'fence_mbarrier_init',
    'fence_proxy',
    'fence_proxy_acquire',
    'fence_proxy_release',
    'fence_proxy_sync_restrict',
    'fence_sc_cluster',
    'fence_sync_restrict',
    'griddepcontrol',
    'log2',
    'mbarrier_arrive_nocomplete',
    'mbarrier_arrive_drop_nocomplete',
    'mbarrier_complete_tx',
    'mbarrier_expect_tx',
    'mbarrier_init',
    'mbarrier_inval',
    'mbarrier_test_wait',
    'mbarrier_try_wait',
    'mbarrier_try_wait_parity',
    'memory_barrier',
    'nanosleep',
    'prefetch',
    'prmt',
    'rcp_approx_ftz_f',
    'read_ptx_sreg_aggr_smem_size',
    'read_ptx_sreg_clock',
    'read_ptx_sreg_clock64',
    'read_ptx_sreg_dynamic_smem_size',
    'read_ptx_sreg_envreg0',
    'read_ptx_sreg_envreg1',
    'read_ptx_sreg_envreg10',
    'read_ptx_sreg_envreg11',
    'read_ptx_sreg_envreg12',
    'read_ptx_sreg_envreg13',
    'read_ptx_sreg_envreg14',
    'read_ptx_sreg_envreg15',
    'read_ptx_sreg_envreg16',
    'read_ptx_sreg_envreg17',
    'read_ptx_sreg_envreg18',
    'read_ptx_sreg_envreg19',
    'read_ptx_sreg_envreg2',
    'read_ptx_sreg_envreg20',
    'read_ptx_sreg_envreg21',
    'read_ptx_sreg_envreg22',
    'read_ptx_sreg_envreg23',
    'read_ptx_sreg_envreg24',
    'read_ptx_sreg_envreg25',
    'read_ptx_sreg_envreg26',
    'read_ptx_sreg_envreg27',
    'read_ptx_sreg_envreg28',
    'read_ptx_sreg_envreg29',
    'read_ptx_sreg_envreg3',
    'read_ptx_sreg_envreg30',
    'read_ptx_sreg_envreg31',
    'read_ptx_sreg_envreg4',
    'read_ptx_sreg_envreg5',
    'read_ptx_sreg_envreg6',
    'read_ptx_sreg_envreg7',
    'read_ptx_sreg_envreg8',
    'read_ptx_sreg_envreg9',
    'read_ptx_sreg_globaltimer',
    'read_ptx_sreg_globaltimer_lo',
    'read_ptx_sreg_lanemask_eq',
    'read_ptx_sreg_lanemask_ge',
    'read_ptx_sreg_lanemask_gt',
    'read_ptx_sreg_lanemask_le',
    'read_ptx_sreg_lanemask_lt',
    'read_ptx_sreg_total_smem_size',
    'setmaxregister',
    'sin',
    'st_bulk',
    'tcgen05_alloc',
    'tcgen05_commit',
    'tcgen05_cp',
    'tcgen05_dealloc',
    'tcgen05_fence',
    'tcgen05_mma_block_scale',
    'tcgen05_mma_sp_block_scale',
    'tcgen05_mma_ws',
    'tcgen05_mma_ws_sp',
    'tcgen05_mma_smem_desc',
    'tcgen05_relinquish_alloc_permit',
    'tcgen05_shift',
    'tcgen05_wait',
    'wgmma_commit_group_sync_aligned',
    'wgmma_fence_aligned',
    'wgmma_wait_group_sync_aligned',
)
